export { PreHeaderComponent } from './pre-header/pre-header.component';
export { FooterComponent } from './footer/footer.component';
export { HeaderComponent } from './header/header.component';
export { SliderComponent } from './slider/slider.component';
export { TableComponent } from './table/table.component';
export { SicPreHeaderComponent } from './sic-pre-header/sic-pre-header.component';
export { SicLangPickerComponent } from './sic-lang-picker/sic-lang-picker.component';
export { SicFooterComponent } from './sic-footer/sic-footer.component';
export { SicHeaderComponent } from './sic-header/sic-header.component';
